<?php

namespace Rts\Bundle\AppMonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppCategoryRepository extends EntityRepository
{
}