RtsAppMonBundle:
    resource: "@RtsAppMonBundle/Controller/"
    type:     annotation
    prefix:   /

RtsUserBundle:
    resource: "@RtsUserBundle/Resources/config/routing.xml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal