# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
RtsAppMonBundle:
    resource: "@RtsAppMonBundle/Controller/"
    type:     annotation
    prefix:   /
