security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    factories:
        - "%kernel.root_dir%/../vendor/fr3d/ldap-bundle/FR3D/LdapBundle/Resources/config/security_factories.xml"

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            providers: [fos_userbundle, fr3d_ldapbundle]
        fos_userbundle:
            id: fos_user.user_manager
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                csrf_provider: form.csrf_provider
                remember_me:   true
            logout:    true
            anonymous: true
            provider: chain_provider
            remember_me:
                lifetime: %login_lifetime%
                key:      %secret%

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
